# Use postgres/example user/password credentials
version: '3.9'

services:

  db:
    image: postgres:15
    ports:
      - 5433:5432
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  postgres_data:/var/lib/postgresql/data  add database info which is in /var/lib/postgresql/data in the container to the volume called postgres_data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

  adminer:
    image: adminer
    ports:
      - 8080:8080